"""empty message

Revision ID: 1134cedc5084
Revises: bb4bbceda972
Create Date: 2020-11-26 21:54:43.015010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1134cedc5084'
down_revision = 'bb4bbceda972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem')
    # ### end Alembic commands ###
