"""empty message

Revision ID: bb4bbceda972
Revises: 
Create Date: 2020-11-01 01:33:11.543305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4bbceda972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('edu', sa.String(length=8), nullable=False),
    sa.Column('school', sa.String(length=8), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal')
    # ### end Alembic commands ###
